### ISSUE TITLE
[Feature Request] Option to remove the Cartographer minimap with item-drop

### ISSUE THREAD

**Issue by RedstoneFuture** [BananaPuncher714/Cartographer2#40]
I was asked by my support if it is possible that the item-drop (with key `Q`, check via `PlayerDropItemEvent`) leads to the map being deleted. In Survival, deleting is not as easy as in creative mode, and we don't want to just drop the minimaps and leave them lying around the survival world.

**Old part in `config.yml`:**
```yml
# Determines whether the player should be allowed to drop the minimap
prevent-drop: true
# Whether or not to use packets or the item drop event
use-drop-packet: true
```

**New part in `config.yml`:**
```yml
# Determines whether the player should be allowed to drop the minimap
prevent-drop: false
# [New] Should item-drop remove the minimap
remove-with-drop: true
# Whether or not to use packets or the item drop event
use-drop-packet: true
```
