### ISSUE TITLE
[Feature Request] (WorldGuard Module) Adding wildcard support for region names

### ISSUE THREAD

**Issue by RedstoneFuture** [BananaPuncher714/Cartographer2#41]
In some servers with many WorldGuard regions, prefixes are used for the region names so that the regions are organized. It would be helpful to have wildcard support for the **WorldGuard Module** of Cartographer2 in the custom color definition so that we don't have to specify each region individually.

**Example:**

```yml
colors:
  regions:
    # custom color for region "shop-1" to "shop-100"
    shop-*:
      nonmember: "#ff9326"
      member: "ff9326"
      owner: "#00FF00"
    *-entrytitel:
      nonmember: "#ff26ff"
      member: "#ff26ff"
      owner: "#00FF00"
```

In most cases, it is sufficient that the wildcard have to be at the beginning (`regionName.endsWith()`) or the end (`regionName.startsWith()`) of the region name.
